### ISSUE TITLE
Name of the package may be a bit confusing

### ISSUE THREAD

**Issue by awesomebytes** [osrf/crocker#4]
Hello, thanks for sharing this package!

I'm just concerned about people googling for it will most probably end up in:

https://github.com/grammarly/rocker

As it was a relatively famous (and very useful) package, now discontinued.

**Comment by tfoote** [comment]
Yes, it may get renamed. It also conflicts with https://github.com/mreithub/rocker though I've asked for access to https://pypi.org/project/rocker/ If I don't get that we'll find a new name.

**Comment by tfoote** [comment]
renamed to crocker

**Comment by tfoote** [comment]
I got permission to take over the pypi rocker project so I'm reverting the name change and hope to document the difference clearly.
